"""Grammar and orthography correction data, generated by reversing normalisation.

Karakalpak has no error-annotated corpus. But Phase 3 normalised everything to
Latin 2016, and the *errors people actually make* are precisely the older
conventions that normalisation removed. Running that transformation backwards
over clean corpus text produces correction pairs whose error distribution is
real rather than invented:

    correct    Qaraqalpaqstan Respublikasınıń paytaxtı — Nókis
    apostrophe Qaraqalpaqstan Respublikasi'ni'n' paytaxti' — No'kis   (2009)
    umlaut     Qaraqalpaqstan Respublikasınıń paytaxtı — Nökis        (1994)
    stripped   Qaraqalpaqstan Respublikasiniń paytaxti — Nokis        (no diacritics)

The *correct* side is genuine corpus text. The *incorrect* side is generated,
so every record is labelled `synthetic=True` - a corrector trained on invented
errors and told they were observed is a corrector nobody can audit.

Corruption is seeded, so the same corpus produces the same dataset.
"""

from __future__ import annotations

import random
import re
from collections.abc import Iterator
from dataclasses import dataclass, field
from enum import StrEnum

from ....common.io import read_jsonl
from ....common.logging import get_logger
from ....dedup.pipeline import output_path
from ....schemas import GrammarRecord, Provenance

logger = get_logger(__name__)

_MIN_CHARS = 40
_MAX_CHARS = 600
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")


class ErrorType(StrEnum):
    """The error being taught. Each mirrors a real writing convention."""

    APOSTROPHE = "orthography_apostrophe"  # 2009 convention
    UMLAUT = "orthography_umlaut"  # 1994 convention
    STRIPPED_DIACRITICS = "orthography_stripped"  # keyboard without the letters
    MIXED = "orthography_mixed"  # some words one way, some another


# Latin 2016 -> Latin 2009 apostrophe forms.
_TO_APOSTROPHE = {"á": "a'", "ó": "o'", "ú": "u'", "ǵ": "g'", "ń": "n'", "ı": "i'",
                  "Á": "A'", "Ó": "O'", "Ú": "U'", "Ǵ": "G'", "Ń": "N'"}

# Latin 2016 -> Latin 1994 umlaut forms.
_TO_UMLAUT = {"á": "ä", "ó": "ö", "ú": "ü", "ń": "ñ", "ǵ": "ģ",
              "Á": "Ä", "Ó": "Ö", "Ú": "Ü", "Ń": "Ñ", "Ǵ": "Ģ"}

# Latin 2016 -> unaccented ASCII, what a plain keyboard produces.
_TO_STRIPPED = {"á": "a", "ó": "o", "ú": "u", "ǵ": "g", "ń": "n", "ı": "i",
                "Á": "A", "Ó": "O", "Ú": "U", "Ǵ": "G", "Ń": "N"}

_EXPLANATIONS = {
    ErrorType.APOSTROPHE: (
        "Házirgi jazıw qaǵıydaları boyınsha apostrof emes, ústin belgili háripler "
        "jazıladı: a' → á, o' → ó, u' → ú, g' → ǵ, n' → ń."
    ),
    ErrorType.UMLAUT: (
        "Eski álipbedegi ä, ö, ü, ñ, ģ háripleriniń ornına házirgi standarttaǵı "
        "á, ó, ú, ń, ǵ háripleri jazıladı."
    ),
    ErrorType.STRIPPED_DIACRITICS: (
        "Ústin belgileri qaldırılmawı kerek: á, ó, ú, ǵ, ń háripleri a, o, u, g, n "
        "háriplerinen ayrıqsha mánige iye."
    ),
    ErrorType.MIXED: (
        "Bir tekstte hár qıylı jazıw qaǵıydaların aralastırıw durıs emes. "
        "Házirgi standart boyınsha ústin belgili háripler jazıladı."
    ),
}

_MARKERS = "áóúǵńıÁÓÚǴŃ"


@dataclass(slots=True)
class GrammarStats:
    read: int = 0
    emitted: int = 0
    skipped_no_markers: int = 0
    skipped_length: int = 0
    by_error: dict[str, int] = field(default_factory=dict)

    def summary(self) -> str:
        return (
            f"grammar: {self.emitted:,} pairs from {self.read:,} sentences "
            f"({self.skipped_no_markers:,} had no correctable letters)"
        )


def corrupt(text: str, error: ErrorType, rng: random.Random) -> str:
    """Apply one writing convention backwards over `text`."""
    if error is ErrorType.APOSTROPHE:
        return "".join(_TO_APOSTROPHE.get(c, c) for c in text)
    if error is ErrorType.UMLAUT:
        return "".join(_TO_UMLAUT.get(c, c) for c in text)
    if error is ErrorType.STRIPPED_DIACRITICS:
        return "".join(_TO_STRIPPED.get(c, c) for c in text)

    # MIXED: corrupt roughly half the words, each with a randomly chosen
    # convention. This is what real transitional text looks like.
    words = text.split(" ")
    tables = (_TO_APOSTROPHE, _TO_UMLAUT, _TO_STRIPPED)
    out: list[str] = []
    for word in words:
        if rng.random() < 0.5:
            table = tables[rng.randrange(len(tables))]
            out.append("".join(table.get(c, c) for c in word))
        else:
            out.append(word)
    return " ".join(out)


def _sentences(text: str) -> Iterator[str]:
    for sentence in _SENTENCE_SPLIT.split(text):
        cleaned = sentence.strip()
        if _MIN_CHARS <= len(cleaned) <= _MAX_CHARS:
            yield cleaned


def build(
    *,
    limit: int | None = None,
    dataset: str = "pretrain_v1",
    seed: int = 20260731,
    include_explanation: bool = True,
    errors: tuple[ErrorType, ...] = tuple(ErrorType),
) -> Iterator[GrammarRecord]:
    """Yield orthography-correction pairs generated from clean corpus text."""
    rng = random.Random(seed)
    stats = GrammarStats()

    provenance = Provenance(
        source_id="grammar_from_orthography",
        license="derived from pretrain_v1; see per-source manifests",
        # The incorrect side is generated. Saying otherwise would make the
        # dataset impossible to audit later.
        synthetic=True,
        generator="qaraqalpaqmind.training.sft.builders.grammar",
        human_reviewed=False,
    )

    for row in read_jsonl(output_path(dataset)):
        if limit is not None and stats.emitted >= limit:
            break

        for sentence in _sentences(str(row.get("text", ""))):
            if limit is not None and stats.emitted >= limit:
                break
            stats.read += 1

            if not any(marker in sentence for marker in _MARKERS):
                # Nothing to correct: corrupting it would produce an identical
                # pair, which the schema rejects and which teaches nothing.
                stats.skipped_no_markers += 1
                continue

            error = errors[rng.randrange(len(errors))]
            incorrect = corrupt(sentence, error, rng)
            if incorrect.strip() == sentence.strip():
                stats.skipped_no_markers += 1
                continue

            yield GrammarRecord(
                incorrect=incorrect,
                correct=sentence,
                explanation=_EXPLANATIONS[error] if include_explanation else "",
                error_type=error.value,
                provenance=provenance,
            )
            stats.emitted += 1
            stats.by_error[error.value] = stats.by_error.get(error.value, 0) + 1

    logger.info("Grammar builder finished", extra={"summary": stats.summary()})
    if stats.by_error:
        logger.info("Grammar error types", extra=dict(stats.by_error))
